name: seqflow-merge

on:
  push:
    branches:
      - main

concurrency: seqflow

permissions:
  contents: write

jobs:
  seqflow-merge:
    runs-on: ubuntu-latest
    steps:
    - name: setup nuget config
      continue-on-error: true
      run: |
        dotnet nuget add source --username ${{ github.triggering_actor }} --password ${{ secrets.MAIN_NUGET_PAT }} --store-password-in-clear-text --name main "https://nuget.pkg.github.com/${{github.repository_owner}}/index.json"
        dotnet nuget add source --username ${{ github.triggering_actor }} --password ${{ secrets.CALQ_FRAMEWORK_NUGET_PAT }} --store-password-in-clear-text --name calq-framework "https://nuget.pkg.github.com/calq-framework/index.json"
    - uses: actions/checkout@v3
      with:
        fetch-depth: 2
    - uses: actions/cache@v3
      with:
        path: ${{ github.workspace }}/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
        restore-keys: |
          ${{ runner.os }}-nuget-
    - uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '5.0.x'
    - name: propagate
      shell: bash
      run: |
        git clone --depth 1 --branch v0.0 https://${{ github.triggering_actor }}:${{ secrets.SEQFLOW_PAT }}@github.com/calq-framework/seqflow.git ./.github/actions/calq-framework/seqflow
        chmod +x ./.github/actions/calq-framework/seqflow/action.sh
        ./.github/actions/calq-framework/seqflow/action.sh merge -r